[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$bodies = git log --format='%B'
$forbidden = '(?i)co-authored-by:.*(codex|openai)|generated by (codex|an ai)|authored by codex'
if (($bodies -join "`n") -match $forbidden) {
	throw 'Forbidden agent authorship text is present in commit history.'
}

git log --format=fuller --max-count=20
